import fs from 'node:fs';
import XLSX from 'xlsx';

const PAGE='https://bip.uke.gov.pl/pozwolenia-radiowe/wykaz-pozwolen-radiowych-tresci/stacje-gsm-umts-lte-5gnr-oraz-cdma,12.html';
const file=process.argv[2]||'android-bts/app/src/main/assets/stations.json';
const base=JSON.parse(fs.readFileSync(file,'utf8'));
const nt=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[łŁ]/g,'l').toLowerCase().trim();
const nk=v=>nt(v).replace(/[^a-z0-9]+/g,'');
const num=v=>{if(typeof v==='number')return v;const m=String(v??'').replace(',','.').match(/-?\d+(?:\.\d+)?/);return m?+m[0]:NaN;};
const clean=s=>String(s??'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
const inferBand=v=>{const t=nt(v).replace(/[_-]+/g,' '),m=t.match(/\b(5g|nr|lte|umts|gsm)\s*\/?\s*-?\s*(\d{3,4})\b/);if(!m)return'';const f=m[1].toUpperCase(),n=m[2];return f==='5G'||f==='NR'?`NR${n}`:`${f}${n}`;};
const bandFreq=b=>{const t=String(b||'').toUpperCase(),m=t.match(/(700|800|850|900|1800|2100|2300|2600|3500|3600|3700|3800)/);if(m)return +m[1];if(t==='NR78')return 3500;if(t==='NR28')return 700;if(t==='NR1')return 2100;if(t==='NR3')return 1800;return 1800;};
const coord=v=>{if(typeof v==='number')return v;const t=String(v??'').trim(),ns=t.replace(/,/g,'.').match(/-?\d+(?:\.\d+)?/g)||[];if(ns.length>=3&&/[°'\"NSWE]/i.test(t)){let x=Math.abs(+ns[0])+Math.abs(+ns[1])/60+Math.abs(+ns[2])/3600;if(/[SW]/i.test(t)||String(ns[0]).startsWith('-'))x*=-1;return x;}return ns.length?+ns[0]:NaN;};
function val(row,patterns){for(const [k,v] of Object.entries(row)){if(patterns.some(p=>typeof p==='string'?k===p:p.test(k))&&String(v??'').trim()!=='')return v;}return'';}
function coords(row){let lat=NaN,lon=NaN;for(const [k,v] of Object.entries(row)){if(!Number.isFinite(lat)&&(k.includes('szerokosc')||k.includes('latitude')||k==='lat'||k==='y'))lat=coord(v);if(!Number.isFinite(lon)&&((k.includes('dlugosc')&&!k.includes('wysokosc'))||k.includes('longitude')||k==='lon'||k==='lng'||k==='x'))lon=coord(v);}if(Number.isFinite(lat)&&Number.isFinite(lon)&&lat>40&&lat<60&&lon>10&&lon<30)return{lat,lon};for(const v of Object.values(row)){const a=String(v||'').replace(/,/g,'.').match(/-?\d+(?:\.\d+)?/g)?.map(Number)||[];for(let i=0;i<a.length-1;i++)if(a[i]>40&&a[i]<60&&a[i+1]>10&&a[i+1]<30)return{lat:a[i],lon:a[i+1]};}return null;}
function op(row){const s=String(val(row,[/uzytkownik/,/operator/,/podmiot/,/przedsiebiorca/])||'Nieznany');if(/orange/i.test(s))return'Orange';if(/t.?mobile/i.test(s))return'T-Mobile';if(/p4|play/i.test(s))return'Play';if(/polkomtel|plus/i.test(s))return'Plus';return s.trim()||'Nieznany';}
function stationId(row){return String(val(row,[/identyfikatorstacji/,/nrstacji/,/nazwastacji/,/siteid/,/nrpozwolenia/,/numerpozwolenia/,/pozwolenie/])||'—').trim();}
function city(row){return String(val(row,[/miejscowosc/,/miasto/,/gmina/])||'').trim();}
function address(row){const d=val(row,[/adresstacji/,/^adres$/, /lokalizacja/]);if(d)return String(d).trim();return [val(row,[/^ulica$/]),city(row),val(row,[/gmina/]),val(row,[/powiat/])].map(x=>String(x||'').trim()).filter(Boolean).join(', ');}
function headerRow(matrix){let best=0,score=-1;for(let i=0;i<Math.min(15,matrix.length);i++){const text=(matrix[i]||[]).map(nt).join(' ');const s=['szer','dlug','operator','uzytk','azymut','erp','moc','anten','stac','pozwol'].filter(k=>text.includes(k)).length;if(s>score){score=s;best=i;}}return best;}
function rows(matrix){const h=headerRow(matrix),headers=(matrix[h]||[]).map((v,i)=>nk(v)||`c${i}`),out=[];for(let i=h+1;i<matrix.length;i++){const r=matrix[i]||[];if(!r.some(v=>String(v??'').trim()))continue;const o={};headers.forEach((k,j)=>o[k]=r[j]??'');out.push(o);}return out;}
function rowStation(row,band,src){const c=coords(row);if(!c)return null;const erp=num(val(row,[/^erp$/, /mocpromieniowana/,/maxmocpromieniowania/]));const az=num(val(row,[/azymut/]));const h=num(val(row,[/^hanteny$/,/wysokosc.*anten/,/wzniesienieanten/]));const tilt=num(val(row,[/elewacja/,/pochylenie/,/tilt/]));const range=num(val(row,[/^robszaru$/,/promienobszaru/,/promien.*obslugi/,/range/]));const eirpDbm=Number.isFinite(erp)?erp+32.15:null;const eirpW=Number.isFinite(eirpDbm)?10**((eirpDbm-30)/10):null;return{station_id:stationId(row),operator:op(row),latitude:c.lat,longitude:c.lon,address:address(row),city:city(row),bands:[band],azimuths:Number.isFinite(az)?[az]:[],range_km:Number.isFinite(range)&&range>0?range:null,power:Number.isFinite(erp)?`${erp} dBW`:'',erp:Number.isFinite(erp)?`${erp} dBW`:'',antenna_height_m:Number.isFinite(h)?h:null,tilt_deg:Number.isFinite(tilt)?tilt:null,records_count:1,source:`UKE ${src}`,param_sources:['UKE'],radio_sectors:[{band,frequency_mhz:bandFreq(band),azimuth_deg:Number.isFinite(az)?az:null,erp_dbw:Number.isFinite(erp)?erp:null,eirp_dbm:eirpDbm,eirp_w:eirpW,height_m:Number.isFinite(h)?h:null,tilt_deg:Number.isFinite(tilt)?tilt:null,range_km:Number.isFinite(range)&&range>0?range:null,source:`UKE ${src}`} ]};}
function distance(a,b){const R=6371.0088,r=x=>x*Math.PI/180,dlat=r(b.latitude-a.latitude),dlon=r(b.longitude-a.longitude),q=Math.sin(dlat/2)**2+Math.cos(r(a.latitude))*Math.cos(r(b.latitude))*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
function uniq(a,b){const out=[];for(const v of [...(a||[]),...(b||[])])if(v!==null&&v!==undefined&&String(v)!==''&&!out.some(x=>nt(x)===nt(v)))out.push(v);return out;}
function merge(t,s){t.bands=uniq(t.bands,s.bands);t.azimuths=uniq(t.azimuths,s.azimuths).map(Number).filter(Number.isFinite).sort((a,b)=>a-b);t.param_sources=uniq(t.param_sources,s.param_sources);t.radio_sectors=uniqSectors([...(t.radio_sectors||[]),...(s.radio_sectors||[])]);t.records_count=(+t.records_count||1)+(+s.records_count||1);if(!t.city&&s.city)t.city=s.city;if(!t.address&&s.address)t.address=s.address;if(!t.power&&s.power)t.power=s.power;if(!t.erp&&s.erp)t.erp=s.erp;if(!Number.isFinite(+t.antenna_height_m)&&Number.isFinite(+s.antenna_height_m))t.antenna_height_m=+s.antenna_height_m;if(!Number.isFinite(+t.tilt_deg)&&Number.isFinite(+s.tilt_deg))t.tilt_deg=+s.tilt_deg;if((!t.range_km||+t.range_km<+s.range_km)&&s.range_km)t.range_km=s.range_km;t.source=[...new Set(String(t.source||'').split(/\s*\|\s*/).concat(String(s.source||'').split(/\s*\|\s*/)).filter(Boolean))].slice(0,8).join(' | ');}
function uniqSectors(arr){const m=new Map();for(const e of arr||[]){const k=[nt(e.band),Number.isFinite(+e.azimuth_deg)?Math.round(+e.azimuth_deg*10):'x',Number.isFinite(+e.erp_dbw)?(+e.erp_dbw).toFixed(1):'x',Number.isFinite(+e.height_m)?(+e.height_m).toFixed(1):'x'].join('|');if(!m.has(k))m.set(k,e);}return [...m.values()];}
async function main(){
  console.log('UKE enrichment: base',base.length);
  let html;try{const r=await fetch(PAGE,{headers:{'user-agent':'BTS-Asystent-PL/1.3 build'}});if(!r.ok)throw new Error('HTTP '+r.status);html=await r.text();}catch(e){console.warn('UKE page unavailable:',e.message);return;}
  const links=[];const re=/<a[^>]+href=["']([^"']+\.xlsx(?:\?[^"']*)?)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const href=new URL(m[1],PAGE).href,name=clean(m[2]),band=inferBand(name+' '+href);if(band&&/(5g|lte|umts|gsm)/i.test(name+' '+href))links.push({href,name,band});}
  const seen=new Set(),files=links.filter(x=>!seen.has(x.href)&&(seen.add(x.href),true));console.log('UKE files:',files.length,files.map(x=>x.band).join(', '));
  const uke=[];for(let i=0;i<files.length;i++){const f=files[i];try{const r=await fetch(f.href,{headers:{'user-agent':'BTS-Asystent-PL/1.3 build'}});if(!r.ok)throw new Error('HTTP '+r.status);const ab=await r.arrayBuffer(),wb=XLSX.read(new Uint8Array(ab),{type:'array'});let count=0;for(const sn of wb.SheetNames){const matrix=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:'',raw:false});for(const row of rows(matrix)){const s=rowStation(row,f.band,f.name);if(s){uke.push(s);count++;}}}console.log(`${i+1}/${files.length} ${f.band}: ${count}`);}catch(e){console.warn('skip',f.band,e.message);}}
  if(!uke.length){console.warn('No UKE records parsed; keep bundled base.');return;}
  const cell=.01,grid=new Map(),gk=(lat,lon,o)=>`${Math.floor(lat/cell)}:${Math.floor(lon/cell)}:${nt(o)}`;const add=(s,i)=>{const k=gk(s.latitude,s.longitude,s.operator);if(!grid.has(k))grid.set(k,[]);grid.get(k).push(i);};base.forEach(add);let matched=0,added=0;
  for(const u of uke){let bi=-1,bd=Infinity;const gy=Math.floor(u.latitude/cell),gx=Math.floor(u.longitude/cell),o=nt(u.operator);for(let y=gy-1;y<=gy+1;y++)for(let x=gx-1;x<=gx+1;x++)for(const i of grid.get(`${y}:${x}:${o}`)||[]){const d=distance(base[i],u);if(d<bd){bd=d;bi=i;}}if(bi>=0&&bd<=.35){merge(base[bi],u);matched++;}else{base.push(u);add(u,base.length-1);added++;}}
  let sectorCount=0,powerStations=0,azStations=0;for(const s of base){if(s.radio_sectors?.length){sectorCount+=s.radio_sectors.length;if(s.radio_sectors.some(e=>Number.isFinite(+e.erp_dbw)||Number.isFinite(+e.eirp_dbm)))powerStations++;if(s.radio_sectors.some(e=>Number.isFinite(+e.azimuth_deg)))azStations++;}}
  fs.writeFileSync(file,JSON.stringify(base));console.log('UKE enrichment done',{ukeRows:uke.length,matched,added,stations:base.length,sectorCount,powerStations,azStations,bytes:fs.statSync(file).size});
}
await main();
